{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "TypeError: 'Worksheet' object is not callable", "trace": "def test_create_auth_with_excel():\n        file_path = \"C:/Users/alate/PycharmProjects/APITestAutomationFramework/tests/test/DataDrivenTesting/TestData_DDTesting.xlsx\"\n>       credencials = read_from_excel(file_path)\n\nDDTesting_ForLoop.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nFileName = 'C:/Users/alate/PycharmProjects/APITestAutomationFramework/tests/test/DataDrivenTesting/TestData_DDTesting.xlsx'\n\n    def read_from_excel(FileName):\n        credentials = []\n        workbook = openpyxl.load_workbook(FileName)\n>       sheet = workbook.active()\nE       TypeError: 'Worksheet' object is not callable\n\nDDTesting_ForLoop.py:14: TypeError"}, "start": 1712586896401, "stop": 1712586896404, "uuid": "97afacff-2d6f-40b8-8c59-7f490d82ad1a", "historyId": "400e86315b4beeffb8fbe6998120a743", "testCaseId": "400e86315b4beeffb8fbe6998120a743", "fullName": "tests.test.DataDrivenTesting.DDTesting_ForLoop#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_ForLoop"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "8952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_ForLoop"}]}