{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "NameError: name 'read_from_excel' is not defined", "trace": "def test_create_auth_with_excel():\n        file_path = \"C:/Users/alate/PycharmProjects/APITestAutomationFramework/tests/test/DataDrivenTesting/TestData_DDTesting.xlsx\"\n>       credencials = read_from_excel(file_path)\nE       NameError: name 'read_from_excel' is not defined\n\nDDTesting_ForLoop.py:40: NameError"}, "start": 1712586980817, "stop": 1712586980817, "uuid": "fd547ca1-4c31-44d6-b315-057ccf81a190", "historyId": "400e86315b4beeffb8fbe6998120a743", "testCaseId": "400e86315b4beeffb8fbe6998120a743", "fullName": "tests.test.DataDrivenTesting.DDTesting_ForLoop#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.DataDrivenTesting"}, {"name": "suite", "value": "DDTesting_ForLoop"}, {"name": "host", "value": "LAPTOP-G6QKH92C"}, {"name": "thread", "value": "20448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.DataDrivenTesting.DDTesting_ForLoop"}]}